name: Build and Analysis

on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  analysis:
    uses: Studi-Grupo3/reuseble-workflows/.github/workflows/node-build.yml@main