name: Build and Analysis

on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  analysis:
    uses: Studi-Grupo3/Front-End/.github/workflows/reusable-ci.yml@develop
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_URL: ${{ secrets.SONAR_URL }}
      SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}