name: Build and Publish Node 

on:
  workflow_dispatch:
    inputs:
      frontend_api_url:
        description: 'URL da API para o frontend (ex: http://34.224.86.136/api)'
        required: false
        type: string
        default: 'http://localhost:8080/api'

jobs:
  call-build:
    id: build
    uses: Studi-Grupo3/reusable-workflows/.github/workflows/node-build.yml@main
    with:
      frontend_api_url: ${{ inputs.frontend_api_url || 'http://localhost:8080/api' }}

  call-publish-release:
    needs: call-build
    runs-on: ubuntu-latest
    uses: Studi-Grupo3/reusable-workflows/.github/workflows/upload-gh-release.yml@main
    with:
      artifact_path: ${{ needs.build.outputs.artifact_path }}
      target_owner_repo: "Studi-Grupo3/artifacts"
      tag: ""
    secrets:
      RELEASE_PAT: ${{ secrets.RELEASE_PAT }}